In [1]:
import numpy as np
import pandas as pd

from scipy.stats import norm

from datetime import date
from datetime import timedelta

from yahoofinancials import YahooFinancials

import warnings
warnings.filterwarnings('ignore')

In [2]:
end = '2021-08-05'
start = '2016-07-21'

In [3]:
weight_df = pd.read_csv('../data/WeightsDF.csv')
weight_df.set_index('Portfolio', inplace=True)

In [4]:
stocks = np.array(weight_df.columns).tolist()

i1 = 0
i2 = 1
portfolio1 = []
portfolio2 = []
for stock in stocks:
    if weight_df[stock][i1] > 0:
        portfolio1.append(stock)
    if weight_df[stock][i2] > 0:
        portfolio2.append(stock)

In [5]:
portfolio_ticker = []
for stock in stocks:
    portfolio_ticker.append(stock+'.NS')

In [6]:
portfolio = []

portfolio.append(portfolio1)
portfolio.append(portfolio2)

portfolio

[['IRCTC',
  'NESTLEIND',
  'INDIAMART',
  'TITAN',
  'INFY',
  'TATACONSUM',
  'TCS',
  'HINDUNILVR',
  'ATGL',
  'DIVISLAB'],
 ['IRCTC',
  'NESTLEIND',
  'INDIAMART',
  'INFY',
  'TATACONSUM',
  'TCS',
  'DIXON',
  'ATGL',
  'DIVISLAB',
  'POLYCAB']]

In [7]:
for stock_name, stock_ticker in zip(stocks, portfolio_ticker):
    
    yf = YahooFinancials(stock_ticker)
    data = yf.get_historical_price_data(start, end, 'daily')
    globals()[stock_name] = pd.DataFrame(data[stock_ticker]['prices'])
    globals()[stock_name] = globals()[stock_name].drop('date', axis=1).set_index('formatted_date')

    globals()[stock_name]['Date'] = pd.to_datetime(globals()[stock_name].index, format="%Y-%m-%d")
    globals()[stock_name].set_index('Date', drop=False, inplace=True)

    globals()[stock_name] = globals()[stock_name].dropna()

In [8]:
closing_df = pd.DataFrame(index=TCS.index, columns=stocks)

for stock in stocks:
    closing_df[stock] = globals()[stock]['adjclose']

In [9]:
yf = YahooFinancials('^NSEI')

data = yf.get_historical_price_data(start, end, 'daily')

nifty_50 = pd.DataFrame(data['^NSEI']['prices'])
nifty_50 = nifty_50.drop('date', axis=1).set_index('formatted_date')

nifty_50['Date'] = pd.to_datetime(nifty_50.index, format="%Y-%m-%d")
nifty_50.set_index('Date', drop=False, inplace=True)

nifty_50 = nifty_50.dropna()
    
nifty_50_daily = nifty_50['adjclose'].pct_change().dropna()

In [10]:
daily_ret = closing_df.pct_change()
daily_ret = daily_ret.dropna()

In [11]:
daily_ret

,IRCTC,NESTLEIND,INDIAMART,TITAN,INFY,TATACONSUM,TCS,DIXON,HINDUNILVR,ATGL,DIVISLAB,POLYCAB
Date,,,,,,,,,,,,
2019-10-15,-0.020062,-0.005801,-0.032453,0.018536,-0.022644,0.007253,0.008065,-0.009072,0.024897,0.005307,0.005583,0.048575
2019-10-16,-0.017528,0.018791,-0.035333,0.001926,0.004100,-0.007921,0.004467,-0.011334,0.003197,-0.020785,0.016006,0.019438
2019-10-17,0.033754,0.011521,-0.001263,0.001961,-0.002528,0.014154,0.012236,0.002849,0.015862,0.002695,0.001599,0.001113
2019-10-18,0.075728,0.021947,0.001959,0.018441,-0.002144,0.009125,0.012999,0.019277,0.001426,0.014785,0.008735,0.005978
2019-10-22,0.084130,0.012440,0.005766,0.022182,-0.153057,-0.000887,-0.002892,-0.030419,0.009730,-0.016887,0.001812,0.037175
...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-29,0.016399,-0.005981,0.008681,0.009051,0.007100,-0.004901,-0.000625,-0.040991,-0.011286,-0.011999,-0.009569,0.012893
2021-07-30,0.004394,-0.011839,-0.000077,-0.014145,-0.004020,0.006723,-0.008871,0.016519,-0.000621,-0.032151,0.012862,0.019782
2021-08-02,0.059023,0.000678,0.017200,0.033245,0.013071,0.004364,0.016401,0.010222,-0.000214,-0.004706,0.004657,0.008213
2021-08-03,-0.000425,0.032146,0.011564,0.038751,0.014495,0.010664,0.020345,-0.017465,0.023170,0.015366,0.015805,0.003752
2021-08-04,0.009441,-0.012401,0.010915,-0.022063,-0.003595,-0.011594,-0.003333,-0.008800,-0.004085,0.001053,-0.008508,-0.030889

In [12]:
corr_stock = daily_ret.copy()
corr_stock['nifty_50'] = nifty_50_daily

In [13]:
corr_stock

,IRCTC,NESTLEIND,INDIAMART,TITAN,INFY,TATACONSUM,TCS,DIXON,HINDUNILVR,ATGL,DIVISLAB,POLYCAB,nifty_50
Date,,,,,,,,,,,,,
2019-10-15,-0.020062,-0.005801,-0.032453,0.018536,-0.022644,0.007253,0.008065,-0.009072,0.024897,0.005307,0.005583,0.048575,0.007684
2019-10-16,-0.017528,0.018791,-0.035333,0.001926,0.004100,-0.007921,0.004467,-0.011334,0.003197,-0.020785,0.016006,0.019438,0.003124
2019-10-17,0.033754,0.011521,-0.001263,0.001961,-0.002528,0.014154,0.012236,0.002849,0.015862,0.002695,0.001599,0.001113,0.010673
2019-10-18,0.075728,0.021947,0.001959,0.018441,-0.002144,0.009125,0.012999,0.019277,0.001426,0.014785,0.008735,0.005978,0.006516
2019-10-22,0.084130,0.012440,0.005766,0.022182,-0.153057,-0.000887,-0.002892,-0.030419,0.009730,-0.016887,0.001812,0.037175,-0.006303
...,...,...,...,...,...,...,...,...,...,...,...,...,...
2021-07-29,0.016399,-0.005981,0.008681,0.009051,0.007100,-0.004901,-0.000625,-0.040991,-0.011286,-0.011999,-0.009569,0.012893,0.004395
2021-07-30,0.004394,-0.011839,-0.000077,-0.014145,-0.004020,0.006723,-0.008871,0.016519,-0.000621,-0.032151,0.012862,0.019782,-0.000976
2021-08-02,0.059023,0.000678,0.017200,0.033245,0.013071,0.004364,0.016401,0.010222,-0.000214,-0.004706,0.004657,0.008213,0.007746
2021-08-03,-0.000425,0.032146,0.011564,0.038751,0.014495,0.010664,0.020345,-0.017465,0.023170,0.015366,0.015805,0.003752,0.015461
2021-08-04,0.009441,-0.012401,0.010915,-0.022063,-0.003595,-0.011594,-0.003333,-0.008800,-0.004085,0.001053,-0.008508,-0.030889,0.007938

In [14]:
corr_df = corr_stock.corr(method='pearson')

In [15]:
corr_df

,IRCTC,NESTLEIND,INDIAMART,TITAN,INFY,TATACONSUM,TCS,DIXON,HINDUNILVR,ATGL,DIVISLAB,POLYCAB,nifty_50
IRCTC,1.000000,0.096468,0.191956,0.247342,0.086067,0.163965,0.094037,0.141394,0.096687,0.144452,0.127812,0.297800,0.289171
NESTLEIND,0.096468,1.000000,0.161013,0.422036,0.366696,0.458887,0.323649,0.248177,0.665013,0.080879,0.347878,0.236600,0.490730
INDIAMART,0.191956,0.161013,1.000000,0.217221,0.199551,0.213065,0.219744,0.278986,0.220743,0.138892,0.253014,0.176522,0.329613
TITAN,0.247342,0.422036,0.217221,1.000000,0.319576,0.438513,0.342658,0.322489,0.314869,0.213155,0.312829,0.398910,0.620362
INFY,0.086067,0.366696,0.199551,0.319576,1.000000,0.411541,0.647243,0.185948,0.388064,0.125413,0.311184,0.253755,0.622951
TATACONSUM,0.163965,0.458887,0.213065,0.438513,0.411541,1.000000,0.352124,0.255208,0.436881,0.264145,0.391538,0.369156,0.612873
TCS,0.094037,0.323649,0.219744,0.342658,0.647243,0.352124,1.000000,0.199700,0.391025,0.171169,0.303622,0.310778,0.610579
DIXON,0.141394,0.248177,0.278986,0.322489,0.185948,0.255208,0.199700,1.000000,0.247458,0.113410,0.163503,0.292487,0.398056
HINDUNILVR,0.096687,0.665013,0.220743,0.314869,0.388064,0.436881,0.391025,0.247458,1.000000,0.088909,0.356859,0.304430,0.511846
ATGL,0.144452,0.080879,0.138892,0.213155,0.125413,0.264145,0.171169,0.113410,0.088909,1.000000,0.161004,0.222267,0.356042
DIVISLAB,0.127812,0.347878,0.253014,0.312829,0.311184,0.391538,0.303622,0.163503,0.356859,0.161004,1.000000,0.220264,0.459462
POLYCAB,0.297800,0.236600,0.176522,0.398910,0.253755,0.369156,0.310778,0.292487,0.304430,0.222267,0.220264,1.000000,0.529376
nifty_50,0.289171,0.490730,0.329613,0.620362,0.622951,0.612873,0.610579,0.398056,0.511846,0.356042,0.459462,0.529376,1.000000

In [16]:
# Beta => Covariance / Variance    OR    (Correlation * Stock_STD) / StandardMarket_STD

stock_beta = pd.Series(index=stocks)
nifty_std = corr_stock['nifty_50'].std()

for stock in stocks:
    stock_beta[stock] = (corr_df['nifty_50'][stock] * corr_stock[stock].std()) / nifty_std

In [17]:
stock_beta

IRCTC         0.517975
NESTLEIND     0.538822
INDIAMART     0.672473
TITAN         0.868372
INFY          0.853918
TATACONSUM    0.897916
TCS           0.719615
DIXON         0.710646
HINDUNILVR    0.578346
ATGL          0.859053
DIVISLAB      0.566313
POLYCAB       0.865348
dtype: float64

In [18]:
metrics = ['Return','Volatility','Sharpe Ratio', 'VaR', 'Portfolio Beta', 'Treynor Ratio', 'Jensen Alpha']
p = ['Portfolio 1', 'Portfolio 2']

max_sharpe = pd.DataFrame(index=metrics)

In [19]:
for portfolios in portfolio:

    daily_retn = daily_ret[portfolios].copy()
    cov_matrixn = daily_retn.cov()
    stock_betan = stock_beta[portfolios].copy()
    
    runs = 50000
    results = np.zeros((7+len(portfolios),runs))
    risk_free_rate = 0.0602
    alpha = 0.01
    days = 252
#     total_investment = 1000000
    market_return = nifty_50_daily.mean() * days 

    for i in range(runs):

        pb = 0

        weights = np.random.random(len(portfolios))
        weights /= np.sum(weights)

        portfolio_return = np.sum(daily_retn.mean()*weights) * days
        portfolio_std_dev = np.sqrt(np.dot(weights.T,np.dot(cov_matrixn, weights))) * np.sqrt(days)

        results[0,i] = portfolio_return
        results[1,i] = portfolio_std_dev

        # SHARPE RATIO => (portfolio_return - risk_free_rate) / volatility
        results[2,i] = (results[0,i] - risk_free_rate) / results[1,i]

        # VaR => return - (Z * volatility)
        results[3,i] = abs(portfolio_return - (portfolio_std_dev * norm.ppf(1 - alpha)))  # ppf => inverse of cdf

        for j in range(len(weights)):
            results[j+7,i] = weights[j]
            pb += weights[j] * stock_betan[j]

        # PORTFOLIO BETA => sum(weight * beta)
        results[4,i] = pb

        # TREYNOR RATIO => (portfolio_return - risk_free_rate) / portfolio_beta
        results[5,i] = (results[0,i] - risk_free_rate) / results[4,i]

        # JENSEN ALPHA => portfolio_return - (risk_free_rate + portfolio_beta * (market_return - risk_free_rate))
        results[6,i] = results[0,i] - (risk_free_rate + results[4,i] * (market_return - risk_free_rate))
    
    a = metrics+portfolios
    
    results = pd.DataFrame(results.T, columns=a)
    
    max_sharpen = results.iloc[results['Sharpe Ratio'].idxmax()]
    
    max_sharpe = pd.concat([max_sharpe, max_sharpen], axis=1)
    
max_sharpe.columns = p

In [20]:
max_sharpe

                Portfolio 1  Portfolio 2
Return             0.755666     0.885953
Volatility         0.249413     0.252839
Sharpe Ratio       2.788412     3.265921
VaR                0.175445     0.297761
Portfolio Beta     0.690775     0.709830
Treynor Ratio      1.006791     1.163311
Jensen Alpha       0.634232     0.762829
IRCTC              0.235017     0.118584
NESTLEIND          0.012083     0.004489
INDIAMART          0.075139     0.098715
TITAN              0.008958          NaN
INFY               0.077063     0.021626
TATACONSUM         0.109025     0.080183
TCS                0.079614     0.056026
HINDUNILVR         0.008036          NaN
ATGL               0.187381     0.143969
DIVISLAB           0.207683     0.155524
DIXON                   NaN     0.262477
POLYCAB                 NaN     0.058406

In [21]:
mcm = max_sharpe.iloc[:7, : ].T

In [22]:
mcw = max_sharpe.iloc[7: , : ].T

In [23]:
mcm

,Return,Volatility,Sharpe Ratio,VaR,Portfolio Beta,Treynor Ratio,Jensen Alpha
Portfolio 1,0.755666,0.249413,2.788412,0.175445,0.690775,1.006791,0.634232
Portfolio 2,0.885953,0.252839,3.265921,0.297761,0.709830,1.163311,0.762829

In [24]:
mcw

,IRCTC,NESTLEIND,INDIAMART,TITAN,INFY,TATACONSUM,TCS,HINDUNILVR,ATGL,DIVISLAB,DIXON,POLYCAB
Portfolio 1,0.235017,0.012083,0.075139,0.008958,0.077063,0.109025,0.079614,0.008036,0.187381,0.207683,NaN,NaN
Portfolio 2,0.118584,0.004489,0.098715,NaN,0.021626,0.080183,0.056026,NaN,0.143969,0.155524,0.262477,0.058406

In [25]:
mcm.to_csv('../data/mcm.csv')
mcw.to_csv('../data/mcw.csv')